version: '3'
services:
  mysql-server:
    container_name: mysql-server
    image: mysql
    ports:
    - 3306:3306
    volumes:
    - ./sql:/docker-initdb.d/
    restart: always
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=test1234
      - MYSQL_DATABASE_HOST='%'
  
  coupon-ms:
    container_name: coupon-ms
    build: ./couponservice/
    depends_on:
      - mysql-server
    ports:
      - 9091:9091
    restart: on-failure
    
  product-ms:
    container_name: product-ms
    build: ./productservice/
    depends_on:
      - mysql-server
      - coupon-ms
    ports:
      - 9090:9090
    restart: on-failure

